--- 
Skillet: 
  parse: html
  url: http://www.skilletstreetfood.com
  sub_nodes: 
    - node:
        - xpath: //div[@class='weekly_feed']//div[@class='date']
    - node:
        - xpath: //div[@class='weekly_feed']//p[@class='description_address']
    - node:
        - xpath: //div[@class='weekly_feed']//p[@class='description_content']

Marination: 
  parse: html
  url: http://marinationmobile.com/locations
  sub_nodes: 
    - node:
        - xpath: //h3
        - regex: s/(\w+)\s-/$1/

Here There Grill: 
  parse: html
  url: http://hereandtheregrill.com/our-locations
  sub_nodes: []

Parfait: 
  parse: gcal
  url: https://www.google.com/calendar/feeds/parfait.icecream@gmail.com/public/basic
  sub_nodes: []

Pai Foods: 
  parse: gcal
  url: https://www.google.com/calendar/feeds/pai@paifoods.com/public/basic
  sub_nodes: []

